### ISSUE TITLE
Does not work with webpack5 flag

### ISSUE THREAD

**Issue by elado** [SolidZORO/next-plugin-antd-less#31]
webpack5 support is still in beta in nextjs. Looks like this plugin fails to load due to some internals changes.

```js
const withAntdLess = require("next-plugin-antd-less");

module.exports = withAntdLess({
  future: {
    webpack5: true,
  },
});
```

```
(node:62355) [DEP_WEBPACK_EXTERNALS_FUNCTION_PARAMETERS] DeprecationWarning: The externals-function should be defined like ({context, request}, cb) => { ... }
(node:62355) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startsWith' of undefined
    at handleExternals (<root>/node_modules/next/build/webpack-config.ts:609:15)
    at Array.webpackConfig.externals._webpack.isWebpack5.require.resolve.paths (<root>/node_modules/next/build/webpack-config.ts:755:21)
    at config.externals (<root>/node_modules/next-plugin-antd-less/index.js:146:24)
    at <root>/node_modules/next/dist/compiled/webpack/bundle5.js:48316:21
```

**Comment by SolidZORO** [comment]
Yes, the webpack5 ecosystem is currently unstable and still in beta in next.js, so I don't plan to support it yet. I will be compatible when it is stable.

**Comment by giscafer** [comment]
same error in next 10.1.0, plugin v0.3.0

**Comment by SolidZORO** [comment]
> same error in next 10.1.0, plugin v0.3.0

@giscafer  can you show me more error info?

**Comment by giscafer** [comment]
> > same error in next 10.1.0, plugin v0.3.0
> 
> @giscafer can you show me more error info?

upgrade to latest version it works fine
