### ISSUE TITLE
Failed to use webpack 5 configuration on Next 11

### ISSUE THREAD

**Issue by nelsliu9121** [SolidZORO/next-plugin-antd-less#62]
Next.js 11 announced recently and it is making webpack 5 the default bundler. The `future.webpack5` config in `next.config.js` has been moved to `webpack5` and it is set to `true` by default. ([see this](https://nextjs.org/docs/messages/webpack5))

To reproduce, go to this [CodeSandbox](https://codesandbox.io/s/next-plugin-antd-less-next11-reproduce-4vwof)

This is the error printed when running `npm run dev`:
```
(node:5223) [DEP_WEBPACK_EXTERNALS_FUNCTION_PARAMETERS] DeprecationWarning: The externals-function should be defined like ({context, request}, cb) => { ... }
(node:5223) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startsWith' of undefined
    at handleExternals (/Users/nelsliu9121/Codes/next-plugin-antd-less-next11-reproduction/node_modules/next/dist/build/webpack-config.js:48:23)
    at Array.webpackConfig.externals._webpack.isWebpack5.require.resolve.paths (/Users/nelsliu9121/Codes/next-plugin-antd-less-next11-reproduction/node_modules/next/dist/build/webpack-config.js:87:77)
    at webpackConfig.externals (/Users/nelsliu9121/Codes/next-plugin-antd-less-next11-reproduction/node_modules/next-plugin-antd-less/overrideWebpackConfig.js:337:62)
    at /Users/nelsliu9121/Codes/next-plugin-antd-less-next11-reproduction/node_modules/next/dist/compiled/webpack/bundle5.js:53948:21
    at deprecated (internal/util.js:89:15)
    at handleExternals (/Users/nelsliu9121/Codes/next-plugin-antd-less-next11-reproduction/node_modules/next/dist/compiled/webpack/bundle5.js:54095:8)
    at next (/Users/nelsliu9121/Codes/next-plugin-antd-less-next11-reproduction/node_modules/next/dist/compiled/webpack/bundle5.js:54073:9)
    at handleExternals (/Users/nelsliu9121/Codes/next-plugin-antd-less-next11-reproduction/node_modules/next/dist/compiled/webpack/bundle5.js:54078:7)
    at /Users/nelsliu9121/Codes/next-plugin-antd-less-next11-reproduction/node_modules/next/dist/compiled/webpack/bundle5.js:54175:5
    at Hook.eval [as callAsync] (eval at create (/Users/nelsliu9121/Codes/next-plugin-antd-less-next11-reproduction/node_modules/next/dist/compiled/webpack/bundle5.js:31934:10), <anonymous>:35:1)
```

**Comment by morellodev** [comment]
I analyzed the issue, the lib does the test `nextConfig.config.future && nextConfig.config.future.webpack5` to enable the Webpack 5 config. Moreover, in Next.js 11+ the flag to explicitly disable Webpack 5 has been moved as a top level property on the Next.js configuration.
