### ISSUE TITLE
Cannot find module '/path/.next/fallback-build-manifest.json'

### ISSUE THREAD

**Issue by danhnguyeen** [SolidZORO/next-plugin-antd-less#64]
Hi there!

After I update the `next.config.js` and `.babelrc.js`
I got this message when running `yarn dev` command

Could you please help?

```
Error: Cannot find module '/Volumes/Data/projects/server/nextjs-admin/.next/fallback-build-manifest.json'
Require stack:
- /Volumes/Data/projects/server/nextjs-admin/node_modules/next/dist/next-server/server/load-components.js
- /Volumes/Data/projects/server/nextjs-admin/node_modules/next/dist/next-server/server/api-utils.js
- /Volumes/Data/projects/server/nextjs-admin/node_modules/next/dist/next-server/server/next-server.js
- /Volumes/Data/projects/server/nextjs-admin/node_modules/next/dist/server/next.js
- /Volumes/Data/projects/server/nextjs-admin/node_modules/next/dist/server/lib/start-server.js
- /Volumes/Data/projects/server/nextjs-admin/node_modules/next/dist/cli/next-dev.js
- /Volumes/Data/projects/server/nextjs-admin/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)
    at Function.mod._resolveFilename (/Volumes/Data/projects/server/nextjs-admin/node_modules/next/dist/build/webpack/require-hook.js:4:1855)
    at Function.Module._load (internal/modules/cjs/loader.js:863:27)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at loadDefaultErrorComponents (/Volumes/Data/projects/server/nextjs-admin/node_modules/next/dist/next-server/server/load-components.js:1:652)
    at DevServer.renderErrorToHTML (/Volumes/Data/projects/server/nextjs-admin/node_modules/next/dist/next-server/server/next-server.js:139:962)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DevServer.render (/Volumes/Data/projects/server/nextjs-admin/node_modules/next/dist/next-server/server/next-server.js:75:160) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Volumes/Data/projects/server/nextjs-admin/node_modules/next/dist/next-server/server/load-components.js',
    '/Volumes/Data/projects/server/nextjs-admin/node_modules/next/dist/next-server/server/api-utils.js',
    '/Volumes/Data/projects/server/nextjs-admin/node_modules/next/dist/next-server/server/next-server.js',
    '/Volumes/Data/projects/server/nextjs-admin/node_modules/next/dist/server/next.js',
    '/Volumes/Data/projects/server/nextjs-admin/node_modules/next/dist/server/lib/start-server.js',
    '/Volumes/Data/projects/server/nextjs-admin/node_modules/next/dist/cli/next-dev.js',
    '/Volumes/Data/projects/server/nextjs-admin/node_modules/next/dist/bin/next'
  ]
}
```

This is my `package.json`

```
{
  "name": "nextjs-admin",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "antd": "^4.16.3",
    "next": "11.0.0",
    "next-plugin-antd-less": "^1.3.0",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
  "devDependencies": {
    "eslint": "7.28.0",
    "eslint-config-next": "11.0.0"
  }
}
```

**Comment by SolidZORO** [comment]
try clear cache, `rm -rf /Volumes/Data/projects/server/nextjs-admin/.next/` ?

this problem may not be caused by next-plugin-antd-less.

**Comment by danhnguyeen** [comment]
Hi @SolidZORO , 
I found that I had to install `babel-plugin-import` package and it's working now. 
Thanks for your reply. Have a nice day :)
